### ISSUE TITLE
Wrong path template matching

### ISSUE THREAD

**Issue by vanta** [smartrecruiters/openapi-first#7]
According to OpenAPI spec (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#pathsObject) there is a possibility to have two endpoints like below:
```
- /pets/{petId}
- /pets/mine
```
and one without template (`/mine`) should match when requesting `/pets/mine`. Currently in OAF it is not the case.

**Comment by kiebzak** [comment]
@vanta , openapi-first does not have it's own routing mechanisms. It depends solely on the web app framework used in the application, which in your case probably is express. In express, the order of the routes applied to the app/router is important because it follows 'first come, first served' rule. openapi-first iterates over your OAS 3.0 specification and for each operation (in order they appear in spec) it applies all declared openapi middlewares to the web app framework instance you use, using express-like route methods (i.e. `router.get`, `router.post`, `router.put` etc.).

So, in your case, it won't work if you specify operation in following order:
```
- /pets/{petId}
- /pets/mine
```
but it will work for this order:
```
- /pets/mine
- /pets/{petId}
```

Please let me know if this explanation resolves your issue.

**Comment by kiebzak** [comment]
@vanta I think I finally understood what the problem is. I did not realise it before because I was focused on `controllers` in which when you terminate the express middleware stack by sending response to the client this issue does not appear (provided you have correct, `express` friendly order of routes in your OAS 3 API specification). But indeed, it was a problem if `openapi-middleware` was calling `next` callback and paths are inclusive (like /pets/mine falls into /pets/{id}) but PR references above should fix it. Feel free to review it and thanks for spotting this!

**Comment by vanta** [comment]
Wow, @kiebzak thanks for the update :)
